# Generated by Django 5.2.2 on 2025-06-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['order', 'featured', '-updated'], 'permissions': [('free', 'Free Perm'), ('premium', 'Premium Perm'), ('team', 'Team Perm'), ('team_pro', 'Team Pro Perm'), ('enterpriee', 'Enterprise Perm')]},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['free', 'premium', 'team', 'team_pro', 'enterpriee'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
